# Generated by Django 3.2.4 on 2021-07-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['industry_name'],
            },
        ),
        migrations.CreateModel(
            name='SubIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.industry')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('companies', models.ManyToManyField(to='api_basic.Company')),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='sub_industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basic.subindustry'),
        ),
    ]
